# Generated by Django 5.1.7 on 2025-04-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_livre_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
                ('isbn_number', models.CharField(max_length=13)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(max_length=2)),
                ('isborrowed', models.BooleanField(default=False)),
            ],
        ),
    ]
