# Generated by Django 5.1.7 on 2025-04-15 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
